### ISSUE TITLE
求助，运行时报错

### ISSUE THREAD

**Issue by tongyifan** [thundernet8/YouzanPayPortal#3]
➞  npm run start                                                                                          [git:master] ✖  []

> youzanpayportal@1.0.0 start /home/tongyifan/YouzanPayPortal
> mkdirp logs && npm run build && cross-env NODE_ENV=production forever start dist/app.js

> youzanpayportal@1.0.0 build /home/tongyifan/YouzanPayPortal
> rimraf dist && tsc

events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: spawn forever ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:379:16)
    at process._tickCallback (internal/process/next_tick.js:114:19)
    at Function.Module.runMain (module.js:692:11)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:207:12)
    at onErrorNT (internal/child_process.js:379:16)
    [... lines matching original stack trace ...]
    at bootstrap_node.js:666:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! youzanpayportal@1.0.0 start: `mkdirp logs && npm run build && cross-env NODE_ENV=production forever start dist/app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the youzanpayportal@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tongyifan/.npm/_logs/2018-06-13T12_29_25_581Z-debug.log

===============================
➞  tail /home/tongyifan/.npm/_logs/2018-06-13T12_29_25_581Z-debug.log                                     [git:master] ✖  []
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "start"
18 verbose node v9.10.1
19 verbose npm  v5.7.1
20 error code ELIFECYCLE
21 error errno 1
22 error youzanpayportal@1.0.0 start: `mkdirp logs && npm run build && cross-env NODE_ENV=production forever start dist/app.js`
22 error Exit status 1
23 error Failed at the youzanpayportal@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

===============================
ArchLinux kernel 4.15.14
node version:v9.10.1
npm version:5.7.1
如能解决不胜感激！！

**Comment by hyxtj001** [comment]
安装forever. npm install forever -g

**Comment by tongyifan** [comment]
@hyxtj001 非常感谢！
